# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: NSEME 2019
email: rlb9fd@virginia.edu
description: >- # this means to ignore newlines until "baseurl:"
  In its seventh year, the National Student Electronic Music Event solicits
  works for its annual conference on February 8-9, 2019 at the University 
  of Virginia in Charlottesville, VA. Composers currently enrolled as 
  graduate or undergraduate students in a college or university are invited 
  to submit up to two works.
baseurl: "/nseme2019/" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  thely

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

collections:
  - features

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
